/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DM3-1-16
 */
public class Ariekta3 extends javax.swing.JFrame {

    /**
     * Creates new form Ariekta3
     */
    public Ariekta3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        numGroup = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        binarybut = new javax.swing.JRadioButton();
        octalbut = new javax.swing.JRadioButton();
        decimalbut = new javax.swing.JRadioButton();
        hexadecimalbut = new javax.swing.JRadioButton();
        textbox = new javax.swing.JTextField();
        textboxnum = new javax.swing.JTextField();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        numGroup.add(binarybut);
        binarybut.setText("Binary");
        binarybut.setToolTipText("Binary");
        binarybut.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AtoB(evt);
            }
        });
        binarybut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binarybutActionPerformed(evt);
            }
        });

        numGroup.add(octalbut);
        octalbut.setText("Octal");
        octalbut.setToolTipText("Octal");
        octalbut.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AtoB4(evt);
            }
        });

        numGroup.add(decimalbut);
        decimalbut.setSelected(true);
        decimalbut.setText("Decimal");
        decimalbut.setToolTipText("Decimal");
        decimalbut.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AtoB(evt);
            }
        });

        numGroup.add(hexadecimalbut);
        hexadecimalbut.setText("Hexadecimal");
        hexadecimalbut.setToolTipText("Hexadecimal");
        hexadecimalbut.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AtoB(evt);
            }
        });

        textbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textboxKeyReleased(evt);
            }
        });

        textboxnum.setText("/10");
        textboxnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textboxnumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hexadecimalbut)
                    .addComponent(decimalbut)
                    .addComponent(octalbut)
                    .addComponent(binarybut)
                    .addComponent(textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textboxnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textboxnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(binarybut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(octalbut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(decimalbut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hexadecimalbut)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textboxnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textboxnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textboxnumActionPerformed

    private void binarybutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binarybutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_binarybutActionPerformed

    private void AtoB(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AtoB
        // TODO add your handling code here:
        if (binarybut.isSelected())
        {
            textboxnum.setText("2");
            textbox.setText(Integer.toBinaryString(num));
        }
        else if (octalbut.isSelected())
        {
            textboxnum.setText("8");
            textbox.setText(Integer.toOctalString(num));
        }
        else if (decimalbut.isSelected())
        {
            textboxnum.setText("10");
            textbox.setText(Integer.toString(num));
        }
        else if (hexadecimalbut.isSelected())
        {
            textboxnum.setText("16");
            textbox.setText(Integer.toHexString(num));
        }
    }//GEN-LAST:event_AtoB

    private void textboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textboxKeyReleased
        // TODO add your handling code here:
        String texto = textbox.getText();
        
        int base = 0;
        if (binarybut.isSelected())
            base = 2;
        else if (octalbut.isSelected())
            base = 8;
        else if (decimalbut.isSelected())
            base = 10;
        else if (hexadecimalbut.isSelected())
            base = 16;
        try 
        {
            num = Integer.parseInt(texto, base);
        }
        catch(NumberFormatException error1)
        {
            
        }
    }//GEN-LAST:event_textboxKeyReleased

    private void AtoB4(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AtoB4
        // TODO add your handling code here:
        if (binarybut.isSelected())
        {
            textboxnum.setText("2");
            textbox.setText(Integer.toBinaryString(num));
        }
        else if (octalbut.isSelected())
        {
            textboxnum.setText("8");
            textbox.setText(Integer.toOctalString(num));
        }
        else if (decimalbut.isSelected())
        {
            textboxnum.setText("10");
            textbox.setText(Integer.toString(num));
        }
        else if (hexadecimalbut.isSelected())
        {
            textboxnum.setText("16");
            textbox.setText(Integer.toHexString(num));
        }
    }//GEN-LAST:event_AtoB4

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ariekta3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ariekta3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ariekta3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ariekta3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ariekta3().setVisible(true);
            }
        });
    }

    private int num; //declaramos esta variable fuera porque necesitamos esta variable que esta en otra funcion
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton binarybut;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton decimalbut;
    private javax.swing.JRadioButton hexadecimalbut;
    private javax.swing.JTextField jTextField3;
    private javax.swing.ButtonGroup numGroup;
    private javax.swing.JRadioButton octalbut;
    private javax.swing.JTextField textbox;
    private javax.swing.JTextField textboxnum;
    // End of variables declaration//GEN-END:variables
}
